<?php

abstract class PowerFlag
{
	// None
    const None = 0;

	// Access admin panel and toolbars
    const Panel = 1;

	// View list of users' snippets
    const ViewSnippets = 2;

	// View list of users' favourites
    const ViewFavourites = 4;

	// View snippets with visibility set to 'private'
    const ViewPrivateSnippet = 8;

	// Delete comments
    const DeleteComment = 16;

	// Delete snippets
    const DeleteSnippet = 32;

	// Ban users
    const BanUser = 64;

	// Unban users
    const UnbanUser = 128;
}

return
[
	'power_flags' => PowerFlag::class,
	'timeout_types' => ['api_key_generation', 'api_access', 'user_creation', 'user_sign_in_attempt',
		'snippet_submission', 'comment_submission'],
	'timeout_lengths' =>
	[
		'api_key_generation' => 600,
		'user_creation' => 14400,
		'user_sign_in' => 15,
		'snippet_submission' => 30,
		'comment_submission' => 15
	],
	'alert_types' => ['success', 'warning', 'error', 'info'],
    'visibility_modes' => ['public', 'private', 'unlisted'],
	'languages' =>
    [
        '1c',
        'abnf',
        'accesslog',
        'actionscript',
        'ada',
        'angelscript',
        'apache',
        'applescript',
        'arcade',
        'arduino',
        'armasm',
        'asciidoc',
        'aspectj',
        'autohotkey',
        'autoit',
        'avrasm',
        'awk',
        'axapta',
        'bash',
        'basic',
        'bnf',
        'brainfuck',
        'cal',
        'capnproto',
        'ceylon',
        'clean',
        'clojure-repl',
        'clojure',
        'cmake',
        'coffeescript',
        'coq',
        'cos',
        'cpp',
        'crmsh',
        'crystal',
        'cs',
        'csp',
        'css',
        'd',
        'dart',
        'delphi',
        'diff',
        'django',
        'dns',
        'dockerfile',
        'dos',
        'dsconfig',
        'dts',
        'dust',
        'ebnf',
        'elixir',
        'elm',
        'erb',
        'erlang-repl',
        'erlang',
        'excel',
        'fix',
        'flix',
        'fortran',
        'fsharp',
        'gams',
        'gauss',
        'gcode',
        'gherkin',
        'glsl',
        'gml',
        'go',
        'golo',
        'gradle',
        'groovy',
        'haml',
        'handlebars',
        'haskell',
        'haxe',
        'hsp',
        'htmlbars',
        'http',
        'hy',
        'inform7',
        'ini',
        'irpf90',
        'isbl',
        'java',
        'javascript',
        'jboss-cli',
        'json',
        'julia-repl',
        'julia',
        'kotlin',
        'lasso',
        'ldif',
        'leaf',
        'less',
        'lisp',
        'livecodeserver',
        'livescript',
        'llvm',
        'lsl',
        'lua',
        'makefile',
        'markdown',
        'mathematica',
        'matlab',
        'maxima',
        'mel',
        'mercury',
        'mipsasm',
        'mizar',
        'mojolicious',
        'monkey',
        'moonscript',
        'n1ql',
        'nginx',
        'nimrod',
        'nix',
        'nsis',
        'objectivec',
        'ocaml',
        'openscad',
        'oxygene',
        'parser3',
        'perl',
        'pf',
        'pgsql',
        'php',
        'plaintext',
        'pony',
        'powershell',
        'processing',
        'profile',
        'prolog',
        'properties',
        'protobuf',
        'puppet',
        'purebasic',
        'python',
        'q',
        'qml',
        'r',
        'reasonml',
        'rib',
        'roboconf',
        'routeros',
        'rsl',
        'ruby',
        'ruleslanguage',
        'rust',
        'sas',
        'scala',
        'scheme',
        'scilab',
        'scss',
        'shell',
        'smali',
        'smalltalk',
        'sml',
        'sqf',
        'sql',
        'stan',
        'stata',
        'step21',
        'stylus',
        'subunit',
        'swift',
        'taggerscript',
        'tap',
        'tcl',
        'tex',
        'thrift',
        'tp',
        'twig',
        'typescript',
        'vala',
        'vbnet',
        'vbscript-html',
        'vbscript',
        'verilog',
        'vhdl',
        'vim',
        'x86asm',
        'xl',
        'xml',
        'xquery',
        'yaml',
        'zephir'
    ]
];
